### ISSUE TITLE
java.sql.SQLException: Error opening connection

### ISSUE THREAD

**Issue by YSaxon** [ubfx/BinDiffHelper#17]
Opening a BinDiff file produces the following error:

```
java.sql.SQLException: Error opening connection
---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: /opt/homebrew/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 11.0.16.1
OS: Mac OS X 12.6 aarch64
```

## DETAILS ##

Starting from the `Window->BinDiffHelper->Open File` window, if I select another file to Diff with, it successfully does the diffing (as recorded in the log), and then throws the error (see below), and if instead I try `Use External BinDiff file`, then it just throws the exception right away. 

```
2022-12-27 | 17:26:28 | DEBUG | (BinDiffHelperPlugin) >Similarity: 99.2663% (Confidence: 99.2723%)
2022-12-27 | 17:26:28 | DEBUG | (BinDiffHelperPlugin) >Writing results: 0.24s
2022-12-27 | 17:26:28 | DEBUG | (BinDiffHelperPlugin) end of output
2022-12-27 | 17:26:28 | DEBUG | (BinDiffHelperPlugin) looking for bindiff at /var/folders/hj/68fwp4b938b48xtwv5b53qhc0000gn/T/[REDACTED]1809_bdh6371567438421441770_vs_[REDACTED]_bdh17155261722763722847.BinDiff
2022-12-27 | 17:26:28 | ERROR | (BinDiffHelperProvider) Error: : java.sql.SQLException: Error opening connection
```

**Comment by nevenoomo** [comment]
I get the same issue on Ghidra 11

**Comment by ubfx** [comment]
> I get the same issue on Ghidra 11

Are you on MacOS, too?

**Comment by nevenoomo** [comment]
> > I get the same issue on Ghidra 11
> 
> Are you on MacOS, too?

Yes, it is on MacOS as well. The architecture is the same.

**Comment by TheZ3ro** [comment]
I get this too using Ghidra 11, MacOS on an ARM M1.

Any workaround?

**Comment by ubfx** [comment]
Unfortunately I have no access to a Mac which is why I wasn't able to reproduce this. But I read [here](https://stackoverflow.com/questions/70048681/java-sql-sqlexception-error-opening-connection), that M1 support was not available in the older versions of the sqlite driver. I built a version of the plugin with the newest version of sqlite-jdbc, maybe one of you on Apple Silicon can give it a try and if that solves the problem, I'll make a proper release.

[ghidra_11.1.2_PUBLIC_20240801_BinDiffHelper.zip](https://github.com/user-attachments/files/16458082/ghidra_11.1.2_PUBLIC_20240801_BinDiffHelper.zip)

**Comment by TheZ3ro** [comment]
It does indeed works! Thanks for the update :)

**Comment by ubfx** [comment]
This should now be properly fixed in the release https://github.com/ubfx/BinDiffHelper/releases/tag/v0.6.0
